import { Container, SectionDivider, SectionHeadTitleWithImage, SectionProductThemes, ServiceAchievementCard } from "@/components/shared";
import { Metadata } from "next";
import { TServiceAchieveCard } from "@/components/shared/cards/service-achievement-card";
import TitleRoomImage from "../../public/assets/images/services-page/services-page-title-room.png"; 
import RestRoomImage from "../../public/assets/images/services-page/services-page-rest-room.jpeg";
import ConsultRoomImage from "../../public/assets/images/services-page/services-page-consult-room.jpeg";
import ConferenceRoomImage from "../../public/assets/images/services-page/services-page-conference-room.jpeg";


export const metadata: Metadata = {
  title: "Dananz | Services",
  description: "Generated by create next app",
};

type TServiceCard = TServiceAchieveCard & {
  id: number;
}
const serviceCardList: TServiceCard[] = [
  {
    id: 1,
    imageUrl: RestRoomImage,
    imageAlt: "Rest room",
    title: "Interior design",
    description:
      "Customize your interior design into a dream place with the best designers and quality furniture. We try our best to fulfill your expectations.",
  },
  {
    id: 2,
    imageUrl: ConsultRoomImage,
    imageAlt: "Consultant room",
    title: "Consultant",
    description:
      "Customize your interior design into a dream place with the best designers and quality furniture. We try our best to fulfill your expectations.",
  },
  {
    id: 3,
    imageUrl: ConferenceRoomImage,
    imageAlt: "Conference room",
    title: "Construction consultant",
    description:
      "Customize your interior design into a dream place with the best designers and quality furniture. We try our best to fulfill your expectations.",
  },
];
export default function Services() {
  return (
    <Container>
      <section>
        <SectionHeadTitleWithImage
          pageName="Services"
          description="It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout."
          imageUrl={TitleRoomImage}
          imageAlt="Title room"
        />
      </section>
      <section>
        <div className="mb-20">
          <SectionDivider name="Achievement" className="mb-10" />
          <div className="flex flex-col gap-10">
            {serviceCardList.map((item) => (
              <ServiceAchievementCard key={item.id} {...item} />
            ))}
          </div>
        </div>
      </section>
      <SectionProductThemes />
    </Container>
  );
}