import { Achievements, Container, SectionHeadTitleWithImage, SectionTitleWithDivider, SectionWhyChooseUs } from "@/components/shared";
import Image from "next/image";
import ConferenceRoomImage from "../../public/assets/images/about-page/about-page-conference-room.png";
import KitchenOnSeaImage from "../../public/assets/images/about-page/about-page-kitchen-on-the-sea.png";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Dananz | About us",
  description: "Generated by create next app",
};

export default function About() {
  return (
    <Container>
      <section>
        <SectionHeadTitleWithImage
          pageName="About"
          description="It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout."
          imageUrl={ConferenceRoomImage}
          imageAlt=""
        />
      </section>
      <section>
        <SectionTitleWithDivider
          sectionName="Achievement"
          text="interior customization with Danaanz, best quality with professional workers"
        />
        <div className="md:flex gap-5 mb-20">
          <div className="mb-5 md:mb-0">
            <Image src={KitchenOnSeaImage} alt="Kitchen on the sea" />
          </div>
          <Achievements className="" />
        </div>
      </section>
      <SectionWhyChooseUs />
    </Container>
  );
}