import {Poppins} from "next/font/google";
import type { Metadata } from "next";
import "./globals.css";
import { Header } from "@/components/shared/header";

const poppins = Poppins({
  subsets: ['latin'],
  variable: "--font-poppins",
  weight: ["400", "500", "600", "700"],
});


export const metadata: Metadata = {
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link data-rh="true" rel="icon" href="/sofa.png" />
      </head>
      <body className={poppins.className}>
        <Header />
        {children}
      </body>
    </html>
  );
}
