import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Dananz | Home",
  description: "Generated by create next app",
};

export default function Home() {
  return (
    <h1>Danaz project begin</h1>
  );
}
