import { Container, PortfolioCard, PortfolioDetailsTemplate, SectionDivider, SectionHeadTitleWithImage,SectionWhyChooseUs } from "@/components/shared";
import { Metadata } from "next";





export const metadata: Metadata = {
  title: "Dananz | Portfolio Details",
  description: "Generated by create next app",
};



export default async function PortfolioDetails({params}: {params: Promise<{url: string}>}) {

const url = (await params).url;

  return (
    <Container>
      <PortfolioDetailsTemplate url={url} />
    </Container>
  );
}