import { Container, PortfolioListItems, SectionDivider, SectionHeadTitleWithImage,SectionWhyChooseUs } from "@/components/shared";
import { Metadata } from "next";

import WorkPlaceImage from "../../public/assets/images/portfolio-page/portfolio-page-work-place.png";



export const metadata: Metadata = {
  title: "Dananz | Portfolio",
  description: "Generated by create next app",
};



export default function Portfolio() {
  return (
    <Container>
      <section>
        <SectionHeadTitleWithImage
          pageName="Portfolio"
          description="It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout."
          imageUrl={WorkPlaceImage}
          imageAlt="Work place"
        />
      </section>

      <section>
        <div className="mb-20">
          <SectionDivider name="Portfolio" className="mb-10" />
          <PortfolioListItems />
        </div>
      </section>

      <SectionWhyChooseUs />
    </Container>
  );
}